packages:
  device: !include device.yaml # include our test device setup

external_components:
  - source:
      type: local
      path: components

# Enable logging
logger:
  level: VERBOSE

sensor:
  - platform: vl53l1x_sensor
    name: Empty sensor
    timing_budget: 20ms
    distance_mode: LONG

i2c:
  sda: 4
  scl: 5
