packages:
  device: !include device.yaml # include our test device setup

external_components:
  - source:
      type: local
      path: components

sensor:
  - platform: vl53l1x_sensor
    name: Empty sensor

i2c:
  sda: 4
  scl: 5
