name: Verify

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master

jobs:
  compile:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make compile script executable
        run: chmod +x ./compile.sh

      - name: Run compile script
        run: ./compile.sh
